### ISSUE TITLE
Support Calico and Flannel out-of-the-box

### ISSUE THREAD

**Issue by jhunt** [jhunt/k8s-boshrelease#11]
It would be nice if we could support either calico or flanneld out of the box.  Perhaps this is a thing we do in the `control` VM, via spec:

```
instance_groups:
  - name: k8s
    release: k8s
    jobs:
      - name: control
        properties:
          networking: calico # or "flannel"
```
