### ISSUE TITLE
Add Metric-server

### ISSUE THREAD

**Issue by obeyler** [jhunt/k8s-boshrelease#38]
To be able to use Horizontal pos autoscaling (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/), metric-server need to be installed inside the cluster.
May we can add it inside the control plane like cert-manager.

**Comment by jhunt** [comment]
Since this is just a YAML apply, it can definitely go in the same way cert-manager does.

See https://github.com/kubernetes-sigs/metrics-server#deployment for installation steps.

**Comment by obeyler** [comment]
It's not really same as cert manager as it also needs to add args on kube-api server to enable aggregation layer
```
    jobs:
    - name: control
      properties:
        apiserver:
          flags:
          - enable-aggregator-routing: true
          - requestheader-client-ca-file: /var/vcap/jobs/control/tls/ca/cert.pem
          - requestheader-allowed-names: ""
          - requestheader-extra-headers-prefix: X-Remote-Extra-
          - requestheader-group-headers: X-Remote-Group
          - requestheader-username-headers: X-Remote-User
          - proxy-client-cert-file: /var/vcap/data/k8s/certs/api/cert.pem
          - proxy-client-key-file: /var/vcap/data/k8s/certs/api/key.pem
```
