### ISSUE TITLE
Support Additional CoreDNS (plugin) Configuration

### ISSUE THREAD

**Issue by obeyler** [jhunt/k8s-boshrelease#62]
Feature:  give the opportunity to add plugin inside configmap of coredns config 
Why : by example some plugin like `hosts` see https://coredns.io/plugins/hosts/ can be very useful to allows coredns to add hosts file to get ip from bosh topology
or forward see https://coredns.io/plugins/forward/

```
     forward internal.paas. /etc/resolv.conf {                                                                                                                                         │
         policy sequential                                                                                                                                                             │
     }                                                                                                                                                                                 │
     hosts bosh.  /etc/hostsFromNode                                                                                                                                                   │

```
We can be inspired by helm template https://github.com/helm/charts/blob/6878cfd32d2240dbd907a77786d28842f6d120a0/stable/coredns/templates/configmap.yaml#L21-L25 to do that

**Comment by jhunt** [comment]
Would it make sense to just add an embeddable property?

i.e.:

```
    properties:
      coredns:
        extra-config: |
          hosts bosh. /etc/hosts/FromNode
```

rather than invent a new syntax via BOSH job properties?

**Comment by obeyler** [comment]
easiest flexible and good idea :-)

**Comment by obeyler** [comment]
or if you want more constrain structure as you've done for mirror of containerd a set of named attributes
 ```
properties:
  coredns:
    plugins:
      forward:
        parameters: "internal.paas. /etc/resolv.conf" 
        block:  |
          policy sequential
      hosts: 
        parameters: " bosh. /etc/hosts/FromNode"
        block: {}

```

**Comment by jhunt** [comment]
check out https://github.com/jhunt/k8s-boshrelease/pull/63, @obeyler

**Comment by obeyler** [comment]
we also need a way to add extra volume to be able to give the `hosts` file from node to the pod
```
      extraVolumes:
      - name: hostsfromnode
        hostPath:
          path: /etc/hosts
          type: File
      extraVolumeMounts:
      - name: hostsfromnode
        mountPath: "/etc/hostsFromNode"

```
